import requests
resp = requests.get("https://www.whitehouse.gov/the-press-office/remarks-president-barack-obama-address-joint-session-congress")
print (resp.url)
print(len(resp.text))
print(resp.text.count('Applause'))
resp1 = requests.get("https://www.whitehouse.gov/the-press-office/remarks-president-state-union-address")
print (resp1.url)
print(len(resp1.text))
print(resp1.text.lower().count('applause'))
resp2 = requests.get("https://www.whitehouse.gov/the-press-office/2011/01/25/remarks-president-state-union-address")
print (resp2.url)
print(len(resp2.text))
print(resp2.text.lower().count('applause'))
resp3 = requests.get("https://www.whitehouse.gov/the-press-office/2012/01/24/remarks-president-state-union-address")
print (resp3.url)
print(len(resp3.text))
print(resp3.text.lower().count('applause'))
resp4 = requests.get("https://www.whitehouse.gov/the-press-office/2013/02/12/remarks-president-state-union-address")
print (resp4.url)
print(len(resp4.text))
print(resp4.text.lower().count('applause'))
resp5 = requests.get("https://www.whitehouse.gov/the-press-office/2014/01/28/president-barack-obamas-state-union-address")
print (resp5.url)
print(len(resp5.text))
print(resp5.text.lower().count('applause'))
resp6 = requests.get("https://www.whitehouse.gov/the-press-office/2015/01/20/remarks-president-state-union-address-january-20-2015")
print (resp6.url)
print(len(resp6.text))
print(resp6.text.lower().count('applause'))
resp7 = requests.get("https://www.whitehouse.gov/the-press-office/2016/01/12/remarks-president-barack-obama-%E2%80%93-prepared-delivery-state-union-address")
print (resp7.url)
print(len(resp7.text))
print(resp7.text.lower().count('applause'))